# Generated by Django 5.1.3 on 2025-05-11 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 5, 11, 12, 10, 1, 959782))),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
