# Generated by Django 5.1.3 on 2025-05-11 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('N', 'Новости'), ('U', 'Обновления')], max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 11, 12, 19, 11, 99177)),
        ),
    ]
