# Generated by Django 5.1.3 on 2025-05-11 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_alter_news_category_alter_news_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 11, 12, 24, 20, 101623)),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
