# Generated by Django 5.1.3 on 2026-04-28 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0005_goods_alter_news_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 29, 2, 56, 9, 577315)),
        ),
    ]
