# Generated by Django 6.0.4 on 2026-05-08 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0006_alter_news_created_date_forum_comment_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.AlterField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 8, 6, 52, 58, 90225)),
        ),
    ]
