# Generated by Django 5.1.3 on 2026-04-29 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0006_alter_goods_img_alter_news_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='img',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 29, 3, 18, 34, 115018)),
        ),
    ]
