# Generated by Django 5.1.3 on 2026-04-30 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0009_forumtopic_alter_news_created_date_forumpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AlterField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 1, 1, 20, 32, 617121)),
        ),
        migrations.DeleteModel(
            name='ForumPost',
        ),
        migrations.DeleteModel(
            name='ForumTopic',
        ),
    ]
